### PR TITLE
Suppress diffs with spacing changes

### LINKED ISSUE #5: Whitespace changes showing diff
```
  ~ resource "mimirtool_ruler_namespace" "mimir" {
      ~ config_yaml                 = <<-EOT
            - name: a
              rules:
                - alert: a
          -       expr: sum(rate(grpc_server_handled_total{grpc_code!="",grpc_service="Service",job="a",namespace="a"}[4m])) < 1.67
          +       expr: |-
          +         sum(rate(grpc_server_handled_total{grpc_code!="",grpc_service="tService",job="a",namespace="a"}[4m])) < 1.67
                  for: 10m
                - alert: b
          -       expr: sum(rate(grpc_server_handled_total{grpc_code!="",grpc_service="dapr.proto.runtime.v1.AppCallback",job="b",namespace="a"}[4m])) < 1.67
          +       expr: |-
          +         sum(rate(grpc_server_handled_total{grpc_code!="",grpc_service="dapr.proto.runtime.v1.AppCallback",job="b",namespace="a"}[4m])) < 1.67
                  for: 10m
        EOT
        id                          = "d9065d6da185ec28758619fc14b755f740043e1060d342aacef26f459fae8d9d"
        # (2 unchanged attributes hidden)
    }
```

I edited out some of our internal names. The provider is generating a diff when using `|-` syntax in a yaml file Terraform loads in

### PR DESCRIPTION
**Pull request by nijave**
Fixes #5

### CODE REVIEW

**Comment by wilfriedroset** [comment]
Thank you for your contribution. We are in the process of rewriting the acceptance test to not rely on mocks as this is not rely how we should have done them in the first place. We aim to use several mimir instances instead, this way we are 100% sure of the behavior of the provider against different version.

You can have a look at the PR right here: https://github.com/ovh/terraform-provider-mimirtool/pull/8
I hope the rebase will be simple enough and not imply more work on your end as your changes are most welcomed :pray:

**Comment by wilfriedroset** [comment]
@nijave The acceptance test refacto has been merge. Would you be able to rebase on main and see how does your proposal works without the mock?

**Comment by nijave** [comment]
> @nijave The acceptance test refacto has been merge. Would you be able to rebase on main and see how does your proposal works without the mock?

Alright, done. The test cases changed a bit since I'm using `rules.LintExpressions` to do the formatting/normalizing instead of the old yaml formatting code. This also leads to a SHA change--not sure if that's problematic

**Review by wilfriedroset — APPROVED** [review]

**Review by vaxvms — APPROVED** [review]

**Comment by vaxvms** [comment]
Thanks for your contribution. Can you sign it for me to be able to merge it ?

**Comment by nijave** [comment]
> Thanks for your contribution. Can you sign it for me to be able to merge it ?

Hi, I think I've done that correctly now

**Pull request merged**
